[package]
name = "loopslcr-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "loopslcr"
path = "src/main.rs"

[dependencies]
loopslcr-core.workspace = true
clap.workspace = true
rayon = "1.12.0"
clap_complete = "4.6.8"

[dev-dependencies]
loopslcr-core = { path = "../loopslcr-core" }
